### PR TITLE
Singhdj2 patch 1

### PR DESCRIPTION
**Pull request by singhdj2**

### CODE REVIEW

**Comment by frahikLV** [comment]
Hello @singhdj2 Thank you for your contribution, I was interested that you take only the values of the first trait, why do you do that? and if you have a case in which that need, to be reproduced because I think this can affect the predictions if you want to take several features. 

To the reproduced case you can use the Iranian data include in the package:

``` R
data("WheatIranianToy")
geno <- genoIranianToy
pheno <- phenoIranianToy
```

Also, why not use ´BME()´ function?

**Comment by singhdj2** [comment]
Hi @frahik, You can ignore the changes I have made to the code as I was not sure if this is the right way to do it. I was simply trying to implement a CV scenario where an entire set of lines from single environment for a particular trait (e.g. yield) are masked. The BMTME throws an error in this scenario. I was thinking if it is possible to change the masking of the one environment from first trait only. When I mask the full set of environment it gives the following error: 

"Error in eigen(Re) : infinite or missing values in 'x' "

Do  you have any suggestion how to fix this issue?  Let me know if you need a reproducible use case to test it on your system. Thanks.

-Daljit

**Comment by frahikLV** [comment]
This is implemented at BMORS model

```
  data('MaizeToy')
  phenoMaizeToy <- phenoMaizeToy[order(phenoMaizeToy$Env, phenoMaizeToy$Line),]
  LG <- cholesky(genoMaizeToy)
  ZG <- model.matrix(~0 + as.factor(phenoMaizeToy$Line))
  Z.G <- ZG %*% LG
  ETA <- list(Gen = list(X = Z.G, model = 'BRR'))

  dataset <- phenoMaizeToy[, 2:5] #Must Include in the first column the environments

  # Check predictive capacities of the model
  pm <- BMORS_Env(dataset, testingEnv = 'EBU', ETA = ETA, covModel = 'BRR', nIter = 10,
                  burnIn = 4, thin = 2, progressBar = FALSE, digits = 3)
```

**Comment by frahikLV** [comment]
Also, if you want to do this with the BMTME model, consider use the following code:

```
data("WheatIranianToy")

  LG <- cholesky(genoIranianToy)
  ZG <- model.matrix(~0 + as.factor(phenoIranianToy$GID))
  Z.G <- ZG %*% LG
  Z.E <- model.matrix(~0 + as.factor(phenoIranianToy$Env))
  ZEG <- model.matrix(~0 + as.factor(phenoIranianToy$GID):as.factor(phenoIranianToy$Env))
  G2 <- kronecker(diag(length(unique(phenoIranianToy$Env))), data.matrix(genoIranianToy))
  LG2 <- cholesky(G2)
  Z.EG <- ZEG %*% LG2
  Y <- as.matrix(phenoIranianToy[, -c(1, 2)])
  fm <- coreMTME(Y, X, Z1, Z2, nIter, burnIn, thin, bs, digits, progressBar = FALSE, testingSet)
```

**Comment by singhdj2** [comment]
If I understand this correct, the BMTME masks testing lines for not just one but all traits. I am particularly interested in a scenario where only a set of lines are masked from just one trait e.g. yield masked from one environment only, meaning the rest of the traits and environments predict yield at one masked environment.
correct me if I am wrong, BMORS_ENV doesn't use full trait information for prediction. So it is technically single-trait multi-environment model?

**Comment by frahikLV** [comment]
> correct me if I am wrong, BMORS_ENV doesn't use full trait information for prediction. So it is technically single-trait multi-environment model?

Correct

I hope to be able to release a feature that will help you solve your implementation next week, greetings

**Pull request closed without merging**
